wavefront_planner_node:
  Subscribed_Topics:
    goal: "/move_base_simple/goal"
    occupancy_map: "/map"

  Published_Topics:
    global_path: "path"
    inflated_map: "/map_inflated"

  Parameters:
    ## Frame Ids
    base_frameId: "base_link"
    map_frameId: "map"

    ## Occupancy Map
    use_map_from_image: true
    image_path: $(find wavefront_planner)/config/sample.png
    grid_resolution: 0.1
    occupancy_free_threshold: 0.3
    occupancy_occupied_threshold: 0.70
    inflation_radius: 0.5

    ## Cycle Time
    path_update_duration: 0.05 # 20Hz
    map_visualize_duration: 2.0

    ## Wavefront search
    search_unknown_option: false # Set false for faster planning
